version: "3.9"

services:
  dns-proxy:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: dns_proxy
    ports:
      - "5300:5300/udp"
    volumes:
      - ./db:/app/db
      - ./logs:/app/logs
    restart: unless-stopped
