version: "3.9"

services:
  dns-proxy:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: dns_proxy
    ports:
      - "53:53/udp"
    cap_add:
      - NET_BIND_SERVICE
    volumes:
      - ./db:/app/db
      - ./category_db:/app/category_db
      - ./logs:/app/logs
    restart: unless-stopped

  dashboard:
    build:
      context: .
      dockerfile: docker/Dockerfile.dashboard
    container_name: dns_dashboard
    ports:
      - "8000:8000"
    volumes:
      - ./db:/app/db
      - ./logs:/app/logs
    restart: unless-stopped